object frmMain: TfrmMain
  Left = 0
  Top = 0
  BorderStyle = bsSingle
  Caption = #1040#1056#1052' '#1062#1055#1055#1053
  ClientHeight = 631
  ClientWidth = 808
  Color = clBtnFace
  DoubleBuffered = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  Menu = MainMenu1
  OldCreateOrder = False
  Position = poDesktopCenter
  WindowState = wsMaximized
  OnActivate = FormActivate
  OnClose = FormClose
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object PageControl1: TPageControl
    Left = 0
    Top = 0
    Width = 808
    Height = 631
    ActivePage = tsSchema
    Align = alClient
    Style = tsFlatButtons
    TabOrder = 0
    ExplicitWidth = 783
    ExplicitHeight = 526
    object tsObjects: TTabSheet
      Caption = #1054#1073#1098#1077#1082#1090#1099' '#1080' '#1076#1072#1090#1095#1080#1082#1080
      ExplicitWidth = 791
      ExplicitHeight = 533
      object Panel1: TPanel
        Left = 0
        Top = 0
        Width = 800
        Height = 289
        Align = alTop
        BevelKind = bkFlat
        BevelOuter = bvNone
        TabOrder = 0
        ExplicitWidth = 791
        object Panel3: TPanel
          Left = 0
          Top = 0
          Width = 796
          Height = 35
          Align = alTop
          BevelKind = bkFlat
          BevelOuter = bvNone
          TabOrder = 0
          ExplicitWidth = 787
          object BitBtn4: TBitBtn
            Left = 8
            Top = 0
            Width = 30
            Height = 30
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Tahoma'
            Font.Style = []
            Glyph.Data = {
              AE060000424DAE06000000000000360000002800000017000000170000000100
              18000000000078060000C40E0000C40E00000000000000000000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFDFDECECECDBDBDBD4D4D4D7D7
              D7E3E3E3F7F7F7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7F7F79F9F9F1C1C1C202020
              4343435353534D4D4D3434340A0A0A5A5A5AD1D1D1FFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFBF12121269
              6969DFDFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFBA9A9A9222222616161
              FBFBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8D8D
              8D161616DDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFEFEFE878787232323F2F2F2FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFF9C9C9C232323F3F3F3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFACACAC252525FCFCFCFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFE0E0E00B0B0BF1F1F1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFF4F4F4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8989896060
              60FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF454545B1B1B1FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFF141414FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFEFEFE242424D2D2D2FFFFFFFFFFFFFFFFFFDFDFDF222222FFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF141414FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFA7A7A7595959FFFFFFFFFFFFFFFFFF9C9C9C
              797979FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF141414FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAFAFA0C0C0CF8F8F8FF
              FFFFFFFFFF424242C6C6C6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFF141414FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FF333333E5E5E5FFFFFFFFFFFF0F0F0FF2F2F2FFFFFFFFFFFFFFFFFFFDFDFDFD
              FDFDFDFDFDFDFDFDFDFDFD141414FDFDFDFDFDFDFDFDFDFDFDFDFDFDFDFFFFFF
              FFFFFFFFFFFFFFFFFF4A4A4AD9D9D9FFFFFFFFFFFF060606FAFAFAFFFFFFFFFF
              FFFFFFFF16161616161616161616161616161602020216161616161616161616
              1616161616F6F6F6FFFFFFFFFFFFFFFFFF4F4F4FD7D7D7FFFFFFFFFFFF222222
              E1E1E1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF141414FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF414141DDDDDDFF
              FFFFFFFFFF696969A5A5A5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFF141414FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FF212121EDEDEDFFFFFFFFFFFFC5C5C54F4F4FFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFF141414FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFDDDDDD1D1D1DFEFEFEFFFFFFFFFFFFF6F6F60E0E0EEAEAEAFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF141414FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF6969699D9D9DFFFFFFFFFFFFFFFFFFFFFFFF
              9898985D5D5DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF141414FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDCDCDC131313F8F8F8FFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFF3A3A3AA4A4A4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F5F5171717C1C1
              C1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3F3F31F1F1FAAAAAAFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1F1F1
              2525258D8D8DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F5
              F53636365D5D5DEBEBEBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFB0B0B00A0A0A9D9D9DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF9696961212124E4E4EA2A2A2E2E2E2F5F5F5F2F2
              F2C5C5C5767676242424474747DFDFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8F8F8C6C6C6646464
              1E1E1E0D0D0D0E0E0E3E3E3E9B9B9BE2E2E2FFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
            ParentFont = False
            TabOrder = 0
            OnClick = BitBtn4Click
          end
          object BitBtn5: TBitBtn
            Left = 80
            Top = 0
            Width = 30
            Height = 30
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Tahoma'
            Font.Style = []
            Glyph.Data = {
              AE060000424DAE06000000000000360000002800000017000000170000000100
              18000000000078060000C40E0000C40E00000000000000000000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFEFEFEFEFEFE
              FEFEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8F8F8B8B8B85E5E5E
              1D1D1D0000000B0B0B3A3A3A8E8E8EDDDDDDFEFEFEFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFE9E9E9E18
              1818575757ABABABE3E3E3FFFFFFF5F5F5CACACA858585202020525252ECECEC
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFD
              FD484848454545E4E4E4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE
              FEFEA9A9A9090909BCBCBCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFEFEFE373737878787FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFE8E8E80B0B0BBDBDBDFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFF6767676E6E6EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE7E7E7090909ECEC
              ECFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD2D2D2191919FAFAFAFFFFFFFFFFFFFF
              FFFFFEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFEFFFFFFFFFFFF
              FFFFFFA8A8A84D4D4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF575757ABABABFFFF
              FFFFFFFFFFFFFFC7C7C7595959FBFBFBFFFFFFFFFFFFFFFFFFFFFFFFCDCDCD31
              3131FFFFFFFFFFFFFFFFFFFDFDFD1F1F1FDDDDDDFFFFFFFFFFFFFFFFFFF5F5F5
              0F0F0FFAFAFAFFFFFFFFFFFFFFFFFFFCFCFC5C5C5C575757FBFBFBFFFFFFFFFF
              FFCECECE161616D2D2D2FFFFFFFFFFFFFFFFFFFFFFFF838383939393FFFFFFFF
              FFFFFFFFFFD7D7D73F3F3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFC555555
              555555FEFEFEDCDCDC111111D1D1D1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCACA
              CA3E3E3EFFFFFFFFFFFFFFFFFFC7C7C75D5D5DFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFDFDFD5151514141410C0C0CDEDEDEFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFF3F3F30F0F0FFFFFFFFFFFFFFFFFFFC3C3C3646464FFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE1E1E1070707444444FDFDFDFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFB060606FFFFFFFFFFFFFFFFFFCDCDCD
              515151FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD3D3D30E0E0EE3E3E34A4A
              4A4F4F4FFCFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE2E2E2222222FFFFFFFF
              FFFFFFFFFFE4E4E4272727FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFCF151515
              D4D4D4FFFFFFFDFDFD565656595959FCFCFCFFFFFFFFFFFFFFFFFFFFFFFFABAB
              AB646464FFFFFFFFFFFFFFFFFFFEFEFE1E1E1EDDDDDDFFFFFFFFFFFFFFFFFFDC
              DCDC161616CFCFCFFFFFFFFFFFFFFFFFFFFCFCFC5959595D5D5DFFFFFFFFFFFF
              FFFFFFFFFFFF545454BBBBBBFFFFFFFFFFFFFFFFFFFFFFFF9999996A6A6AFFFF
              FFFFFFFFFFFFFFF0F0F0DCDCDCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFCC8
              C8C8FFFFFFFFFFFFFFFFFFE4E4E4161616F9F9F9FFFFFFFFFFFFFFFFFFFFFFFF
              FBFBFB1B1B1BD6D6D6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4343439E9E9EFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFD5D5D5090909EDEDEDFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8585854C4C4CFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB0B0B0080808D5D5D5FF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAFAFA6B6B6B
              3A3A3AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFD4D4D41C1C1C666666DDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9F9F9AA
              AAAA1818186B6B6BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFBFBFB9797971D1D1D2424245050505F5F5F5D5D
              5D3C3C3C0D0D0D555555D3D3D3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFEE4E4E4
              CCCCCCC6C6C6C7C7C7D7D7D7F4F4F4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
            ParentFont = False
            TabOrder = 1
            OnClick = BitBtn5Click
          end
          object BitBtn6: TBitBtn
            Left = 44
            Top = 0
            Width = 30
            Height = 30
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Tahoma'
            Font.Style = []
            Glyph.Data = {
              AE060000424DAE06000000000000360000002800000017000000170000000100
              18000000000078060000C40E0000C40E00000000000000000000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFCAAAAAAF9F9F9FFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4D4D4D1414
              14595959D5D5D5FEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFBBBBBBAFAFAFF0F0F0A3A3A34A4A4AFEFEFEFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF4F4F4FDDDDDD272727DFDFDF4D4D4DFCFCFC
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF737373181818FDFDFDFF
              FFFFDDDDDD595959F9F9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FF4A4A4AC0C0C0F0F0F0FFFFFFDADADA5B5B5BFBFBFBFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF525252B9B9B9DADADAFFFFFFDCDCDC4D4D4DFEFE
              FEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFB5C5C5CC4C4C4C1C1C1
              FFFFFFE3E3E3494949FEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA
              FAFA565656D6D6D6B0B0B0FFFFFFE0E0E04A4A4AFEFEFEFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFF4C4C4CDEDEDEBBBBBBFFFFFFE3E3E34D4D4DFB
              FBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B4B4BDCDCDCE5E5
              E5FFFFFFDDDDDD5A5A5AF9F9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFF4C4C4CC3C3C3F3F3F3FFFFFFDADADA5A5A5AFDFDFDFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF575757B6B6B6E4E4E4FFFFFFDEDEDE4D4D4D
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFB5D5D5DC1C1C1C8
              C8C8E0E0E04747474A4A4AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFBFBFB545454B8B8B84F4F4FFEFEFEBABABA4A4A4AFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B4B4BDDDDDDD0D0D06C6C6CBDBDBDB9B9
              B9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B4B4B505050
              FFFFFF979797CCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFF5D5D5D5C5C5C8F8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
            ParentFont = False
            TabOrder = 2
            OnClick = BitBtn6Click
          end
        end
        object DBGridEh1: TDBGridEh
          Left = 0
          Top = 35
          Width = 796
          Height = 250
          Align = alClient
          AutoFitColWidths = True
          Color = cl3DLight
          DataSource = dm.dsObjects
          DrawMemoText = True
          DynProps = <>
          IndicatorOptions = [gioShowRowIndicatorEh]
          OptionsEh = [dghFixed3D, dghHighlightFocus, dghClearSelection, dghAutoSortMarking, dghDialogFind, dghColumnResize, dghColumnMove, dghExtendVertLines]
          ReadOnly = True
          SortLocal = True
          TabOrder = 1
          Columns = <
            item
              DynProps = <>
              EditButtons = <>
              FieldName = 'ID_object'
              Footers = <>
              Visible = False
            end
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Naimenovanie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1053#1072#1080#1084#1077#1085#1086#1074#1072#1085#1080#1077' '#1086#1073#1098#1077#1082#1090#1072
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 300
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Oboznachenie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1054#1073#1086#1079#1085#1072#1095#1077#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 150
            end
            item
              DynProps = <>
              EditButtons = <>
              FieldName = 'Primechanie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1055#1088#1080#1084#1077#1095#1072#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 200
            end>
          object RowDetailData: TRowDetailPanelControlEh
          end
        end
      end
      object Panel2: TPanel
        Left = 0
        Top = 289
        Width = 800
        Height = 311
        Align = alClient
        BevelKind = bkFlat
        BevelOuter = bvNone
        TabOrder = 1
        ExplicitWidth = 791
        ExplicitHeight = 244
        object Panel4: TPanel
          Left = 0
          Top = 0
          Width = 796
          Height = 35
          Align = alTop
          BevelKind = bkFlat
          BevelOuter = bvNone
          ParentBackground = False
          TabOrder = 0
          ExplicitWidth = 787
          object BitBtn1: TBitBtn
            Left = 8
            Top = 0
            Width = 30
            Height = 30
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Tahoma'
            Font.Style = []
            Glyph.Data = {
              AE060000424DAE06000000000000360000002800000017000000170000000100
              18000000000078060000C40E0000C40E00000000000000000000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFDFDECECECDBDBDBD4D4D4D7D7
              D7E3E3E3F7F7F7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7F7F79F9F9F1C1C1C202020
              4343435353534D4D4D3434340A0A0A5A5A5AD1D1D1FFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFBF12121269
              6969DFDFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFBA9A9A9222222616161
              FBFBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8D8D
              8D161616DDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFEFEFE878787232323F2F2F2FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFF9C9C9C232323F3F3F3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFACACAC252525FCFCFCFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFE0E0E00B0B0BF1F1F1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFF4F4F4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8989896060
              60FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF454545B1B1B1FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFF141414FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFEFEFE242424D2D2D2FFFFFFFFFFFFFFFFFFDFDFDF222222FFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF141414FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFA7A7A7595959FFFFFFFFFFFFFFFFFF9C9C9C
              797979FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF141414FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAFAFA0C0C0CF8F8F8FF
              FFFFFFFFFF424242C6C6C6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFF141414FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FF333333E5E5E5FFFFFFFFFFFF0F0F0FF2F2F2FFFFFFFFFFFFFFFFFFFDFDFDFD
              FDFDFDFDFDFDFDFDFDFDFD141414FDFDFDFDFDFDFDFDFDFDFDFDFDFDFDFFFFFF
              FFFFFFFFFFFFFFFFFF4A4A4AD9D9D9FFFFFFFFFFFF060606FAFAFAFFFFFFFFFF
              FFFFFFFF16161616161616161616161616161602020216161616161616161616
              1616161616F6F6F6FFFFFFFFFFFFFFFFFF4F4F4FD7D7D7FFFFFFFFFFFF222222
              E1E1E1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF141414FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF414141DDDDDDFF
              FFFFFFFFFF696969A5A5A5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFF141414FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FF212121EDEDEDFFFFFFFFFFFFC5C5C54F4F4FFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFF141414FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFDDDDDD1D1D1DFEFEFEFFFFFFFFFFFFF6F6F60E0E0EEAEAEAFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF141414FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF6969699D9D9DFFFFFFFFFFFFFFFFFFFFFFFF
              9898985D5D5DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF141414FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDCDCDC131313F8F8F8FFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFF3A3A3AA4A4A4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F5F5171717C1C1
              C1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3F3F31F1F1FAAAAAAFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1F1F1
              2525258D8D8DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F5
              F53636365D5D5DEBEBEBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFB0B0B00A0A0A9D9D9DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF9696961212124E4E4EA2A2A2E2E2E2F5F5F5F2F2
              F2C5C5C5767676242424474747DFDFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8F8F8C6C6C6646464
              1E1E1E0D0D0D0E0E0E3E3E3E9B9B9BE2E2E2FFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
            ParentFont = False
            TabOrder = 0
            OnClick = BitBtn1Click
          end
          object BitBtn2: TBitBtn
            Left = 44
            Top = 0
            Width = 30
            Height = 30
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Tahoma'
            Font.Style = []
            Glyph.Data = {
              AE060000424DAE06000000000000360000002800000017000000170000000100
              18000000000078060000C40E0000C40E00000000000000000000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFCAAAAAAF9F9F9FFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4D4D4D1414
              14595959D5D5D5FEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFBBBBBBAFAFAFF0F0F0A3A3A34A4A4AFEFEFEFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF4F4F4FDDDDDD272727DFDFDF4D4D4DFCFCFC
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF737373181818FDFDFDFF
              FFFFDDDDDD595959F9F9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FF4A4A4AC0C0C0F0F0F0FFFFFFDADADA5B5B5BFBFBFBFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF525252B9B9B9DADADAFFFFFFDCDCDC4D4D4DFEFE
              FEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFB5C5C5CC4C4C4C1C1C1
              FFFFFFE3E3E3494949FEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA
              FAFA565656D6D6D6B0B0B0FFFFFFE0E0E04A4A4AFEFEFEFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFF4C4C4CDEDEDEBBBBBBFFFFFFE3E3E34D4D4DFB
              FBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B4B4BDCDCDCE5E5
              E5FFFFFFDDDDDD5A5A5AF9F9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFF4C4C4CC3C3C3F3F3F3FFFFFFDADADA5A5A5AFDFDFDFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF575757B6B6B6E4E4E4FFFFFFDEDEDE4D4D4D
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFB5D5D5DC1C1C1C8
              C8C8E0E0E04747474A4A4AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFBFBFB545454B8B8B84F4F4FFEFEFEBABABA4A4A4AFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B4B4BDDDDDDD0D0D06C6C6CBDBDBDB9B9
              B9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B4B4B505050
              FFFFFF979797CCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFF5D5D5D5C5C5C8F8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
            ParentFont = False
            TabOrder = 1
            OnClick = BitBtn2Click
          end
          object BitBtn3: TBitBtn
            Left = 80
            Top = 0
            Width = 30
            Height = 30
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'Tahoma'
            Font.Style = []
            Glyph.Data = {
              AE060000424DAE06000000000000360000002800000017000000170000000100
              18000000000078060000C40E0000C40E00000000000000000000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFEFEFEFEFEFE
              FEFEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8F8F8B8B8B85E5E5E
              1D1D1D0000000B0B0B3A3A3A8E8E8EDDDDDDFEFEFEFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFE9E9E9E18
              1818575757ABABABE3E3E3FFFFFFF5F5F5CACACA858585202020525252ECECEC
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFD
              FD484848454545E4E4E4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE
              FEFEA9A9A9090909BCBCBCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFEFEFE373737878787FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFE8E8E80B0B0BBDBDBDFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFF6767676E6E6EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE7E7E7090909ECEC
              ECFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD2D2D2191919FAFAFAFFFFFFFFFFFFFF
              FFFFFEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFEFFFFFFFFFFFF
              FFFFFFA8A8A84D4D4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF575757ABABABFFFF
              FFFFFFFFFFFFFFC7C7C7595959FBFBFBFFFFFFFFFFFFFFFFFFFFFFFFCDCDCD31
              3131FFFFFFFFFFFFFFFFFFFDFDFD1F1F1FDDDDDDFFFFFFFFFFFFFFFFFFF5F5F5
              0F0F0FFAFAFAFFFFFFFFFFFFFFFFFFFCFCFC5C5C5C575757FBFBFBFFFFFFFFFF
              FFCECECE161616D2D2D2FFFFFFFFFFFFFFFFFFFFFFFF838383939393FFFFFFFF
              FFFFFFFFFFD7D7D73F3F3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFC555555
              555555FEFEFEDCDCDC111111D1D1D1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCACA
              CA3E3E3EFFFFFFFFFFFFFFFFFFC7C7C75D5D5DFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFDFDFD5151514141410C0C0CDEDEDEFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFF3F3F30F0F0FFFFFFFFFFFFFFFFFFFC3C3C3646464FFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE1E1E1070707444444FDFDFDFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFB060606FFFFFFFFFFFFFFFFFFCDCDCD
              515151FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD3D3D30E0E0EE3E3E34A4A
              4A4F4F4FFCFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE2E2E2222222FFFFFFFF
              FFFFFFFFFFE4E4E4272727FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFCF151515
              D4D4D4FFFFFFFDFDFD565656595959FCFCFCFFFFFFFFFFFFFFFFFFFFFFFFABAB
              AB646464FFFFFFFFFFFFFFFFFFFEFEFE1E1E1EDDDDDDFFFFFFFFFFFFFFFFFFDC
              DCDC161616CFCFCFFFFFFFFFFFFFFFFFFFFCFCFC5959595D5D5DFFFFFFFFFFFF
              FFFFFFFFFFFF545454BBBBBBFFFFFFFFFFFFFFFFFFFFFFFF9999996A6A6AFFFF
              FFFFFFFFFFFFFFF0F0F0DCDCDCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFCC8
              C8C8FFFFFFFFFFFFFFFFFFE4E4E4161616F9F9F9FFFFFFFFFFFFFFFFFFFFFFFF
              FBFBFB1B1B1BD6D6D6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4343439E9E9EFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFD5D5D5090909EDEDEDFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8585854C4C4CFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB0B0B0080808D5D5D5FF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAFAFA6B6B6B
              3A3A3AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFD4D4D41C1C1C666666DDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9F9F9AA
              AAAA1818186B6B6BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFBFBFB9797971D1D1D2424245050505F5F5F5D5D
              5D3C3C3C0D0D0D555555D3D3D3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFEE4E4E4
              CCCCCCC6C6C6C7C7C7D7D7D7F4F4F4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
            ParentFont = False
            TabOrder = 2
            OnClick = BitBtn3Click
          end
        end
        object DBGridEh2: TDBGridEh
          Left = 0
          Top = 35
          Width = 796
          Height = 272
          Align = alClient
          AutoFitColWidths = True
          Color = cl3DLight
          DataSource = dm.dsSensors
          DrawMemoText = True
          DynProps = <>
          IndicatorOptions = [gioShowRowIndicatorEh]
          OptionsEh = [dghFixed3D, dghHighlightFocus, dghClearSelection, dghAutoSortMarking, dghDialogFind, dghColumnResize, dghColumnMove, dghExtendVertLines]
          ReadOnly = True
          SortLocal = True
          TabOrder = 1
          OnDrawColumnCell = DBGridEh2DrawColumnCell
          Columns = <
            item
              DynProps = <>
              EditButtons = <>
              FieldName = 'ID_datchik'
              Footers = <>
              Title.Alignment = taCenter
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Visible = False
              Width = 150
            end
            item
              DynProps = <>
              EditButtons = <>
              FieldName = 'ID_object'
              Footers = <>
              Title.Alignment = taCenter
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Visible = False
              Width = 150
            end
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Naimenovanie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1053#1072#1080#1084#1077#1085#1086#1074#1072#1085#1080#1077' '#1076#1072#1090#1095#1080#1082#1072
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 250
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Oboznachenie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1054#1073#1086#1079#1085#1072#1095#1077#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 100
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Nomer'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1053#1086#1084#1077#1088' '#1079#1072#1074#1086#1076#1089#1082#1086#1081
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 120
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DisplayFormat = '#,##0.00'
              DynProps = <>
              EditButtons = <>
              FieldName = 'MAX'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1052#1072#1082#1089'. '#1079#1085#1072#1095#1077#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 100
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DisplayFormat = '#,##0.00'
              DynProps = <>
              EditButtons = <>
              FieldName = 'MIN'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1052#1080#1085'. '#1079#1085#1072#1095#1077#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 100
            end
            item
              DynProps = <>
              EditButtons = <>
              FieldName = 'ID_sostoianie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Visible = False
              Width = 150
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Sostoianie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1057#1086#1089#1090#1086#1103#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 100
            end
            item
              DynProps = <>
              EditButtons = <>
              FieldName = 'Primechanie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1055#1088#1080#1084#1077#1095#1072#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 150
            end>
          object RowDetailData: TRowDetailPanelControlEh
          end
        end
      end
    end
    object tsSensors: TTabSheet
      Caption = #1044#1072#1090#1095#1080#1082#1080' '#1080' '#1087#1086#1082#1072#1079#1072#1085#1080#1103
      ImageIndex = 1
      ExplicitWidth = 791
      ExplicitHeight = 533
      object Panel5: TPanel
        Left = 0
        Top = 0
        Width = 800
        Height = 289
        Align = alTop
        BevelKind = bkFlat
        BevelOuter = bvNone
        TabOrder = 0
        ExplicitWidth = 791
        object Panel6: TPanel
          Left = 0
          Top = 0
          Width = 796
          Height = 35
          Align = alTop
          BevelKind = bkFlat
          BevelOuter = bvNone
          TabOrder = 0
          ExplicitWidth = 787
          object BitBtn7: TBitBtn
            Left = 7
            Top = 1
            Width = 30
            Height = 30
            Glyph.Data = {
              AE060000424DAE06000000000000360000002800000017000000170000000100
              18000000000078060000C40E0000C40E00000000000000000000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFDFDECECECDBDBDBD4D4D4D7D7
              D7E3E3E3F7F7F7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7F7F79F9F9F1C1C1C202020
              4343435353534D4D4D3434340A0A0A5A5A5AD1D1D1FFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFBF12121269
              6969DFDFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFBA9A9A9222222616161
              FBFBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8D8D
              8D161616DDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFEFEFE878787232323F2F2F2FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFF9C9C9C232323F3F3F3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFACACAC252525FCFCFCFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFE0E0E00B0B0BF1F1F1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFF4F4F4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8989896060
              60FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF454545B1B1B1FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFF141414FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFEFEFE242424D2D2D2FFFFFFFFFFFFFFFFFFDFDFDF222222FFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF141414FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFA7A7A7595959FFFFFFFFFFFFFFFFFF9C9C9C
              797979FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF141414FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAFAFA0C0C0CF8F8F8FF
              FFFFFFFFFF424242C6C6C6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFF141414FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FF333333E5E5E5FFFFFFFFFFFF0F0F0FF2F2F2FFFFFFFFFFFFFFFFFFFDFDFDFD
              FDFDFDFDFDFDFDFDFDFDFD141414FDFDFDFDFDFDFDFDFDFDFDFDFDFDFDFFFFFF
              FFFFFFFFFFFFFFFFFF4A4A4AD9D9D9FFFFFFFFFFFF060606FAFAFAFFFFFFFFFF
              FFFFFFFF16161616161616161616161616161602020216161616161616161616
              1616161616F6F6F6FFFFFFFFFFFFFFFFFF4F4F4FD7D7D7FFFFFFFFFFFF222222
              E1E1E1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF141414FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF414141DDDDDDFF
              FFFFFFFFFF696969A5A5A5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFF141414FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FF212121EDEDEDFFFFFFFFFFFFC5C5C54F4F4FFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFF141414FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFDDDDDD1D1D1DFEFEFEFFFFFFFFFFFFF6F6F60E0E0EEAEAEAFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF141414FFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF6969699D9D9DFFFFFFFFFFFFFFFFFFFFFFFF
              9898985D5D5DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF141414FFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDCDCDC131313F8F8F8FFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFF3A3A3AA4A4A4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F5F5171717C1C1
              C1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3F3F31F1F1FAAAAAAFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1F1F1
              2525258D8D8DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F5
              F53636365D5D5DEBEBEBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFB0B0B00A0A0A9D9D9DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF9696961212124E4E4EA2A2A2E2E2E2F5F5F5F2F2
              F2C5C5C5767676242424474747DFDFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8F8F8C6C6C6646464
              1E1E1E0D0D0D0E0E0E3E3E3E9B9B9BE2E2E2FFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
            TabOrder = 0
            OnClick = BitBtn7Click
          end
          object BitBtn8: TBitBtn
            Left = 43
            Top = 1
            Width = 30
            Height = 30
            Glyph.Data = {
              AE060000424DAE06000000000000360000002800000017000000170000000100
              18000000000078060000C40E0000C40E00000000000000000000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFCAAAAAAF9F9F9FFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4D4D4D1414
              14595959D5D5D5FEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFBBBBBBAFAFAFF0F0F0A3A3A34A4A4AFEFEFEFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF4F4F4FDDDDDD272727DFDFDF4D4D4DFCFCFC
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF737373181818FDFDFDFF
              FFFFDDDDDD595959F9F9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FF4A4A4AC0C0C0F0F0F0FFFFFFDADADA5B5B5BFBFBFBFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF525252B9B9B9DADADAFFFFFFDCDCDC4D4D4DFEFE
              FEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFB5C5C5CC4C4C4C1C1C1
              FFFFFFE3E3E3494949FEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA
              FAFA565656D6D6D6B0B0B0FFFFFFE0E0E04A4A4AFEFEFEFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFF4C4C4CDEDEDEBBBBBBFFFFFFE3E3E34D4D4DFB
              FBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B4B4BDCDCDCE5E5
              E5FFFFFFDDDDDD5A5A5AF9F9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFF4C4C4CC3C3C3F3F3F3FFFFFFDADADA5A5A5AFDFDFDFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF575757B6B6B6E4E4E4FFFFFFDEDEDE4D4D4D
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFB5D5D5DC1C1C1C8
              C8C8E0E0E04747474A4A4AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFBFBFB545454B8B8B84F4F4FFEFEFEBABABA4A4A4AFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B4B4BDDDDDDD0D0D06C6C6CBDBDBDB9B9
              B9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B4B4B505050
              FFFFFF979797CCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFF5D5D5D5C5C5C8F8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
            TabOrder = 1
            OnClick = BitBtn8Click
          end
          object BitBtn9: TBitBtn
            Left = 79
            Top = 1
            Width = 30
            Height = 30
            Glyph.Data = {
              AE060000424DAE06000000000000360000002800000017000000170000000100
              18000000000078060000C40E0000C40E00000000000000000000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFEFEFEFEFEFE
              FEFEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8F8F8B8B8B85E5E5E
              1D1D1D0000000B0B0B3A3A3A8E8E8EDDDDDDFEFEFEFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFE9E9E9E18
              1818575757ABABABE3E3E3FFFFFFF5F5F5CACACA858585202020525252ECECEC
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFD
              FD484848454545E4E4E4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE
              FEFEA9A9A9090909BCBCBCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFEFEFE373737878787FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFE8E8E80B0B0BBDBDBDFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFF6767676E6E6EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE7E7E7090909ECEC
              ECFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD2D2D2191919FAFAFAFFFFFFFFFFFFFF
              FFFFFEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFEFFFFFFFFFFFF
              FFFFFFA8A8A84D4D4DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF575757ABABABFFFF
              FFFFFFFFFFFFFFC7C7C7595959FBFBFBFFFFFFFFFFFFFFFFFFFFFFFFCDCDCD31
              3131FFFFFFFFFFFFFFFFFFFDFDFD1F1F1FDDDDDDFFFFFFFFFFFFFFFFFFF5F5F5
              0F0F0FFAFAFAFFFFFFFFFFFFFFFFFFFCFCFC5C5C5C575757FBFBFBFFFFFFFFFF
              FFCECECE161616D2D2D2FFFFFFFFFFFFFFFFFFFFFFFF838383939393FFFFFFFF
              FFFFFFFFFFD7D7D73F3F3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFC555555
              555555FEFEFEDCDCDC111111D1D1D1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCACA
              CA3E3E3EFFFFFFFFFFFFFFFFFFC7C7C75D5D5DFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFDFDFD5151514141410C0C0CDEDEDEFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFF3F3F30F0F0FFFFFFFFFFFFFFFFFFFC3C3C3646464FFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE1E1E1070707444444FDFDFDFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFB060606FFFFFFFFFFFFFFFFFFCDCDCD
              515151FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD3D3D30E0E0EE3E3E34A4A
              4A4F4F4FFCFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE2E2E2222222FFFFFFFF
              FFFFFFFFFFE4E4E4272727FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFCF151515
              D4D4D4FFFFFFFDFDFD565656595959FCFCFCFFFFFFFFFFFFFFFFFFFFFFFFABAB
              AB646464FFFFFFFFFFFFFFFFFFFEFEFE1E1E1EDDDDDDFFFFFFFFFFFFFFFFFFDC
              DCDC161616CFCFCFFFFFFFFFFFFFFFFFFFFCFCFC5959595D5D5DFFFFFFFFFFFF
              FFFFFFFFFFFF545454BBBBBBFFFFFFFFFFFFFFFFFFFFFFFF9999996A6A6AFFFF
              FFFFFFFFFFFFFFF0F0F0DCDCDCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFCC8
              C8C8FFFFFFFFFFFFFFFFFFE4E4E4161616F9F9F9FFFFFFFFFFFFFFFFFFFFFFFF
              FBFBFB1B1B1BD6D6D6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4343439E9E9EFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFD5D5D5090909EDEDEDFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8585854C4C4CFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB0B0B0080808D5D5D5FF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAFAFA6B6B6B
              3A3A3AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFD4D4D41C1C1C666666DDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9F9F9AA
              AAAA1818186B6B6BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFBFBFB9797971D1D1D2424245050505F5F5F5D5D
              5D3C3C3C0D0D0D555555D3D3D3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFEE4E4E4
              CCCCCCC6C6C6C7C7C7D7D7D7F4F4F4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
            TabOrder = 2
          end
        end
        object DBGridEh3: TDBGridEh
          Left = 0
          Top = 35
          Width = 796
          Height = 250
          Align = alClient
          AutoFitColWidths = True
          Color = cl3DLight
          DataSource = dm.dsSensorsI
          DrawMemoText = True
          DynProps = <>
          IndicatorOptions = [gioShowRowIndicatorEh]
          OptionsEh = [dghFixed3D, dghHighlightFocus, dghClearSelection, dghAutoSortMarking, dghDialogFind, dghColumnResize, dghColumnMove, dghExtendVertLines]
          ReadOnly = True
          SortLocal = True
          TabOrder = 1
          OnDrawColumnCell = DBGridEh3DrawColumnCell
          Columns = <
            item
              DynProps = <>
              EditButtons = <>
              FieldName = 'ID_datchik'
              Footers = <>
              Title.Alignment = taCenter
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Visible = False
              Width = 100
            end
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Naimenovanie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1053#1072#1080#1084#1077#1085#1086#1074#1072#1085#1080#1077' '#1076#1072#1090#1095#1080#1082#1072
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 200
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Oboznachenie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1054#1073#1086#1079#1085#1072#1095#1077#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 100
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Nomer'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #8470' '#1079#1072#1074#1086#1076#1089#1082#1086#1081
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 100
            end
            item
              DynProps = <>
              EditButtons = <>
              FieldName = 'ID_object'
              Footers = <>
              Title.Alignment = taCenter
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Visible = False
              Width = 100
            end
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Object'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1052#1077#1089#1090#1086#1088#1072#1089#1087#1086#1083#1086#1078#1077#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 200
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DisplayFormat = '#,##0.00'
              DynProps = <>
              EditButtons = <>
              FieldName = 'MAX'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1052#1072#1082#1089'. '#1079#1085#1072#1095#1077#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 100
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DisplayFormat = '#,##0.00'
              DynProps = <>
              EditButtons = <>
              FieldName = 'MIN'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1052#1080#1085'. '#1079#1085#1072#1095#1077#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 100
            end
            item
              DynProps = <>
              EditButtons = <>
              FieldName = 'ID_sostoianie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Visible = False
              Width = 100
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Sostoianie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1057#1086#1089#1090#1086#1103#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 90
            end
            item
              DynProps = <>
              EditButtons = <>
              FieldName = 'Primechanie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1055#1088#1080#1084#1077#1095#1072#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 100
            end>
          object RowDetailData: TRowDetailPanelControlEh
          end
        end
      end
      object Panel7: TPanel
        Left = 0
        Top = 289
        Width = 800
        Height = 311
        Align = alClient
        BevelKind = bkFlat
        BevelOuter = bvNone
        TabOrder = 1
        ExplicitWidth = 791
        ExplicitHeight = 244
        object Panel8: TPanel
          Left = 0
          Top = 0
          Width = 796
          Height = 35
          Align = alTop
          BevelKind = bkFlat
          BevelOuter = bvNone
          TabOrder = 0
          ExplicitWidth = 787
          object BitBtn11: TBitBtn
            Left = 7
            Top = 1
            Width = 30
            Height = 30
            Glyph.Data = {
              AE060000424DAE06000000000000360000002800000017000000170000000100
              18000000000078060000C40E0000C40E00000000000000000000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFCAAAAAAF9F9F9FFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4D4D4D1414
              14595959D5D5D5FEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFBBBBBBAFAFAFF0F0F0A3A3A34A4A4AFEFEFEFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF4F4F4FDDDDDD272727DFDFDF4D4D4DFCFCFC
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF737373181818FDFDFDFF
              FFFFDDDDDD595959F9F9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FF4A4A4AC0C0C0F0F0F0FFFFFFDADADA5B5B5BFBFBFBFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF525252B9B9B9DADADAFFFFFFDCDCDC4D4D4DFEFE
              FEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFB5C5C5CC4C4C4C1C1C1
              FFFFFFE3E3E3494949FEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA
              FAFA565656D6D6D6B0B0B0FFFFFFE0E0E04A4A4AFEFEFEFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFF4C4C4CDEDEDEBBBBBBFFFFFFE3E3E34D4D4DFB
              FBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B4B4BDCDCDCE5E5
              E5FFFFFFDDDDDD5A5A5AF9F9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFF4C4C4CC3C3C3F3F3F3FFFFFFDADADA5A5A5AFDFDFDFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF575757B6B6B6E4E4E4FFFFFFDEDEDE4D4D4D
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFB5D5D5DC1C1C1C8
              C8C8E0E0E04747474A4A4AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFBFBFB545454B8B8B84F4F4FFEFEFEBABABA4A4A4AFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B4B4BDDDDDDD0D0D06C6C6CBDBDBDB9B9
              B9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B4B4B505050
              FFFFFF979797CCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFF5D5D5D5C5C5C8F8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
            TabOrder = 0
            OnClick = BitBtn11Click
          end
        end
        object DBGridEh4: TDBGridEh
          Left = 0
          Top = 35
          Width = 796
          Height = 272
          Align = alClient
          AutoFitColWidths = True
          Color = cl3DLight
          DataSource = dm.dsReadings
          DrawMemoText = True
          DynProps = <>
          IndicatorOptions = [gioShowRowIndicatorEh]
          OptionsEh = [dghFixed3D, dghHighlightFocus, dghClearSelection, dghAutoSortMarking, dghDialogFind, dghColumnResize, dghColumnMove, dghExtendVertLines]
          ReadOnly = True
          SortLocal = True
          TabOrder = 1
          OnDrawColumnCell = DBGridEh4DrawColumnCell
          Columns = <
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'ID_pokazanie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Visible = False
              Width = 100
            end
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'ID_datchik'
              Footers = <>
              Title.Alignment = taCenter
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Visible = False
              Width = 100
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Datavremia'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1044#1072#1090#1072'/'#1074#1088#1077#1084#1103
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 150
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DisplayFormat = '#,##0.00'
              DynProps = <>
              EditButtons = <>
              FieldName = 'Pokazanie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1055#1086#1082#1072#1079#1072#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 150
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Norma'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1053#1086#1088#1084#1072
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Title.TitleButton = True
              Width = 150
            end
            item
              DynProps = <>
              EditButtons = <>
              FieldName = 'Primechanie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1055#1088#1080#1084#1077#1095#1072#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 150
            end>
          object RowDetailData: TRowDetailPanelControlEh
          end
        end
      end
    end
    object tsFailure: TTabSheet
      Caption = #1040#1074#1072#1088#1080#1081#1085#1099#1077' '#1089#1080#1090#1091#1072#1094#1080#1080
      ImageIndex = 2
      ExplicitWidth = 775
      ExplicitHeight = 495
      object Panel9: TPanel
        Left = 0
        Top = 0
        Width = 800
        Height = 265
        Align = alTop
        BevelKind = bkFlat
        BevelOuter = bvNone
        TabOrder = 0
        ExplicitWidth = 775
        object Panel11: TPanel
          Left = 0
          Top = 0
          Width = 796
          Height = 35
          Align = alTop
          BevelKind = bkFlat
          BevelOuter = bvNone
          TabOrder = 0
          ExplicitWidth = 771
          object BitBtn10: TBitBtn
            Left = 8
            Top = 1
            Width = 30
            Height = 30
            Glyph.Data = {
              AE060000424DAE06000000000000360000002800000017000000170000000100
              18000000000078060000C40E0000C40E00000000000000000000FFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFCFCAAAAAAF9F9F9FFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4D4D4D1414
              14595959D5D5D5FEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFBBBBBBAFAFAFF0F0F0A3A3A34A4A4AFEFEFEFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF4F4F4FDDDDDD272727DFDFDF4D4D4DFCFCFC
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF737373181818FDFDFDFF
              FFFFDDDDDD595959F9F9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FF4A4A4AC0C0C0F0F0F0FFFFFFDADADA5B5B5BFBFBFBFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFF525252B9B9B9DADADAFFFFFFDCDCDC4D4D4DFEFE
              FEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFB5C5C5CC4C4C4C1C1C1
              FFFFFFE3E3E3494949FEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA
              FAFA565656D6D6D6B0B0B0FFFFFFE0E0E04A4A4AFEFEFEFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFF4C4C4CDEDEDEBBBBBBFFFFFFE3E3E34D4D4DFB
              FBFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B4B4BDCDCDCE5E5
              E5FFFFFFDDDDDD5A5A5AF9F9F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFF4C4C4CC3C3C3F3F3F3FFFFFFDADADA5A5A5AFDFDFDFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF575757B6B6B6E4E4E4FFFFFFDEDEDE4D4D4D
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFBFB5D5D5DC1C1C1C8
              C8C8E0E0E04747474A4A4AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFBFBFB545454B8B8B84F4F4FFEFEFEBABABA4A4A4AFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B4B4BDDDDDDD0D0D06C6C6CBDBDBDB9B9
              B9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4B4B4B505050
              FFFFFF979797CCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFF5D5D5D5C5C5C8F8F8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
            TabOrder = 0
            OnClick = BitBtn10Click
          end
        end
        object DBGridEh5: TDBGridEh
          Left = 0
          Top = 35
          Width = 796
          Height = 226
          Align = alClient
          AutoFitColWidths = True
          Color = cl3DLight
          DataSource = dm.dsFault
          DrawMemoText = True
          DynProps = <>
          IndicatorOptions = [gioShowRowIndicatorEh]
          OptionsEh = [dghFixed3D, dghHighlightFocus, dghClearSelection, dghAutoSortMarking, dghDialogFind, dghColumnResize, dghColumnMove, dghExtendVertLines]
          ReadOnly = True
          SortLocal = True
          TabOrder = 1
          OnDrawColumnCell = DBGridEh5DrawColumnCell
          Columns = <
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'ID_avaria'
              Footers = <>
              Title.Alignment = taCenter
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Visible = False
              Width = 100
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'DV_obnaruzhena'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1044#1072#1090#1072'/'#1074#1088#1077#1084#1103' '#1072#1074#1072#1088#1080#1080
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 130
            end
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Opisanie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1054#1087#1080#1089#1072#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 180
            end
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'ID_datchik'
              Footers = <>
              Title.Alignment = taCenter
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Visible = False
              Width = 100
            end
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Object'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1053#1072#1080#1084#1077#1085#1086#1074#1072#1085#1080#1077' '#1086#1073#1098#1077#1082#1090#1072
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 150
            end
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'DatchikNaimenovanie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1053#1072#1080#1084#1077#1085#1086#1074#1072#1085#1080#1077' '#1076#1072#1090#1095#1080#1082#1072
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 150
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'DatchikOboznachenie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1054#1073#1086#1079#1085#1072#1095#1077#1085#1080#1077' '#1076#1072#1090#1095#1080#1082#1072
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 140
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Zamechena'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1047#1072#1084#1077#1095#1077#1085#1072
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 70
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'DV_zamechena'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1047#1072#1084#1077#1095#1077#1085#1072' '#1076#1072#1090#1072'/'#1074#1088#1077#1084#1103
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 140
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Ustranena'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1059#1089#1090#1088#1072#1085#1077#1085#1072
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 70
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'DV_ustranena'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1059#1089#1090#1088#1072#1085#1077#1085#1072' '#1076#1072#1090#1072'/'#1074#1088#1077#1084#1103
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 150
            end
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'ID_stepen'
              Footers = <>
              Title.Alignment = taCenter
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Visible = False
              Width = 100
            end
            item
              DynProps = <>
              EditButtons = <>
              FieldName = 'Primechanie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1055#1088#1080#1084#1077#1095#1072#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 100
            end>
          object RowDetailData: TRowDetailPanelControlEh
          end
        end
      end
      object Panel10: TPanel
        Left = 0
        Top = 265
        Width = 800
        Height = 335
        Align = alClient
        BevelKind = bkFlat
        BevelOuter = bvNone
        TabOrder = 1
        ExplicitWidth = 775
        ExplicitHeight = 230
        object Panel12: TPanel
          Left = 0
          Top = 0
          Width = 796
          Height = 35
          Align = alTop
          BevelKind = bkFlat
          BevelOuter = bvNone
          TabOrder = 0
          ExplicitWidth = 771
        end
        object DBGridEh6: TDBGridEh
          Left = 0
          Top = 35
          Width = 796
          Height = 296
          Align = alClient
          AutoFitColWidths = True
          Color = cl3DLight
          DataSource = dm.dsFaultReadings
          DrawMemoText = True
          DynProps = <>
          IndicatorOptions = [gioShowRowIndicatorEh]
          OptionsEh = [dghFixed3D, dghHighlightFocus, dghClearSelection, dghAutoSortMarking, dghDialogFind, dghColumnResize, dghColumnMove, dghExtendVertLines]
          ReadOnly = True
          SortLocal = True
          TabOrder = 1
          Columns = <
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'ID_pokazanie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Visible = False
              Width = 130
            end
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'ID_datchik'
              Footers = <>
              Title.Alignment = taCenter
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Visible = False
              Width = 130
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Datavremia'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1044#1072#1090#1072'/'#1074#1088#1077#1084#1103
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 130
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DisplayFormat = '#,##0.00'
              DynProps = <>
              EditButtons = <>
              FieldName = 'Pokazanie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1055#1086#1082#1072#1079#1072#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 130
            end
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'Norma'
              Footers = <>
              Title.Alignment = taCenter
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Visible = False
              Width = 130
            end
            item
              AutoFitColWidth = False
              DynProps = <>
              EditButtons = <>
              FieldName = 'ID_avaria'
              Footers = <>
              Title.Alignment = taCenter
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Visible = False
              Width = 130
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DisplayFormat = '#,##0.00'
              DynProps = <>
              EditButtons = <>
              FieldName = 'Bolshe_MAX_na'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1041#1086#1083#1100#1096#1077' '#1085#1086#1088#1084#1099' '#1085#1072
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 130
            end
            item
              Alignment = taCenter
              AutoFitColWidth = False
              DisplayFormat = '#,##0.00'
              DynProps = <>
              EditButtons = <>
              FieldName = 'Menshe_MIN_na'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1052#1077#1085#1100#1096#1077' '#1085#1086#1088#1084#1099' '#1085#1072
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 130
            end
            item
              DynProps = <>
              EditButtons = <>
              FieldName = 'Primechanie'
              Footers = <>
              Title.Alignment = taCenter
              Title.Caption = #1055#1088#1080#1084#1077#1095#1072#1085#1080#1077
              Title.Font.Charset = DEFAULT_CHARSET
              Title.Font.Color = clWindowText
              Title.Font.Height = -11
              Title.Font.Name = 'Tahoma'
              Title.Font.Style = [fsBold]
              Width = 130
            end>
          object RowDetailData: TRowDetailPanelControlEh
          end
        end
      end
    end
    object tsSchema: TTabSheet
      Caption = #1052#1085#1077#1084#1086#1089#1093#1077#1084#1072
      ImageIndex = 3
      OnShow = tsSchemaShow
      ExplicitWidth = 791
      ExplicitHeight = 533
      DesignSize = (
        800
        600)
      object Image1: TImage
        Left = 0
        Top = 0
        Width = 800
        Height = 600
        Align = alClient
        OnMouseMove = Image1MouseMove
        ExplicitLeft = 360
        ExplicitTop = 336
        ExplicitWidth = 105
        ExplicitHeight = 105
      end
      object Edit1: TEdit
        Left = 231
        Top = 320
        Width = 36
        Height = 19
        Anchors = []
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -9
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        Text = 'Edit1'
        ExplicitLeft = 228
        ExplicitTop = 283
      end
      object Edit2: TEdit
        Left = 274
        Top = 227
        Width = 36
        Height = 19
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -9
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        Text = 'Edit2'
      end
      object Edit3: TEdit
        Left = 104
        Top = 262
        Width = 36
        Height = 19
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -9
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        Text = 'Edit3'
      end
      object Edit4: TEdit
        Left = 152
        Top = 211
        Width = 47
        Height = 19
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -9
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        Text = 'Edit4'
      end
      object Edit7: TEdit
        Left = 560
        Top = 152
        Width = 121
        Height = 21
        TabOrder = 4
        Text = 'Edit7'
      end
      object Edit8: TEdit
        Left = 560
        Top = 200
        Width = 121
        Height = 21
        TabOrder = 5
        Text = 'Edit8'
      end
      object BitBtn13: TBitBtn
        Left = 576
        Top = 232
        Width = 75
        Height = 25
        Caption = 'BitBtn13'
        TabOrder = 6
        OnClick = BitBtn13Click
      end
    end
    object tsLogin: TTabSheet
      Caption = 'tsLogin'
      ImageIndex = 4
      ExplicitWidth = 791
      ExplicitHeight = 533
      object GroupBox1: TGroupBox
        Left = 320
        Top = 128
        Width = 153
        Height = 169
        Caption = #1042#1093#1086#1076' '#1074' '#1089#1080#1089#1090#1077#1084#1091
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
        object Label1: TLabel
          Left = 16
          Top = 24
          Width = 34
          Height = 13
          Caption = #1051#1086#1075#1080#1085
        end
        object Label2: TLabel
          Left = 16
          Top = 77
          Width = 43
          Height = 13
          Caption = #1055#1072#1088#1086#1083#1100
        end
        object Edit5: TEdit
          Left = 16
          Top = 40
          Width = 121
          Height = 21
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
        end
        object Edit6: TEdit
          Left = 16
          Top = 96
          Width = 121
          Height = 21
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
        end
        object BitBtn12: TBitBtn
          Left = 16
          Top = 131
          Width = 121
          Height = 25
          Caption = #1042#1086#1081#1090#1080
          TabOrder = 2
          OnClick = BitBtn12Click
        end
      end
    end
  end
  object MainMenu1: TMainMenu
    Left = 736
    Top = 24
    object N1: TMenuItem
      Caption = #1060#1072#1081#1083
      object N9: TMenuItem
        Caption = #1042#1099#1093#1086#1076
        OnClick = N9Click
      end
    end
    object N2: TMenuItem
      Caption = #1044#1086#1082#1091#1084#1077#1085#1090#1099
      object N6: TMenuItem
        Caption = #1046#1091#1088#1085#1072#1083' '#1087#1086#1082#1072#1079#1072#1085#1080#1081
        OnClick = N6Click
      end
      object N7: TMenuItem
        Caption = #1046#1091#1088#1085#1072#1083' '#1072#1074#1072#1088#1080#1081#1085#1099#1093' '#1089#1080#1090#1091#1072#1094#1080#1081
        OnClick = N7Click
      end
    end
    object N4: TMenuItem
      Caption = #1042#1089#1087#1086#1084#1086#1075#1072#1090#1077#1083#1100#1085#1099#1077' '#1076#1072#1085#1085#1099#1077
      object N5: TMenuItem
        Caption = #1057#1086#1089#1090#1086#1103#1085#1080#1103' '#1076#1072#1090#1095#1080#1082#1086#1074
        OnClick = N5Click
      end
    end
    object N3: TMenuItem
      Caption = #1055#1086#1084#1086#1097#1100
      object N8: TMenuItem
        Caption = #1054' '#1087#1088#1086#1075#1088#1072#1084#1084#1077
        OnClick = N8Click
      end
    end
  end
end
